insert into category(icon,name,update_field,delete_field)values("atr","Chompas y cárdigans","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Poleras","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Pantalones","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Casacas y abrigos","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Básicos","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Polos y tops","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Blusas y camisas","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Jeans","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Blazers","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Vestidos","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Faldas","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Shorts","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Ropa interior","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Lencería","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Medias y pantys","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Pijamas","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Ropa deportiva","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Ropa de maternidad","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Polos","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Camisas","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Joggers","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Accesorios","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Correas","update","delete");
insert into category(icon,name,update_field,delete_field)values("atr","Shorts","update","delete");

insert into material_type(icon,name,update_field,delete_field)values("snowing","Videla","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Malla","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Tela mojada","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","French Terry","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","French Terry perchado","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Franela","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Aldogon","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Algodon Jersey","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Licra","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Rip","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Kodra","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Full Licra","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Suplex","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Polinam","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Interfil Grueso","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Polifix","update","delete");
insert into material_type(icon,name,update_field,delete_field)values("snowing","Hilo","update","delete");

insert into status(icon,name,update_field,delete_field)values("radio_button_checked","guardado","update","delete");
insert into status(icon,name,update_field,delete_field)values("radio_button_checked","vendido","update","delete");
insert into status(icon,name,update_field,delete_field)values("radio_button_checked","dañado","update","delete");

insert into gender(icon,name,update_field,delete_field)values("pedriatrics","Recien Nacido","update","delete");
insert into gender(icon,name,update_field,delete_field)values("stroller","Bebe Niño","update","delete");
insert into gender(icon,name,update_field,delete_field)values("stroller","Bebe Niña","update","delete");
insert into gender(icon,name,update_field,delete_field)values("boy","Niño","update","delete");
insert into gender(icon,name,update_field,delete_field)values("girl","Niña","update","delete");
insert into gender(icon,name,update_field,delete_field)values("man","Hombre","update","delete");
insert into gender(icon,name,update_field,delete_field)values("woman","Mujer","update","delete");

insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","TOYS CJEstilos","90000000","update","delete");
insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","Ropa CJEstilos","90000000","update","delete");
insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","Generico","900000000","update","delete");
insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","YEY","900000000","update","delete");
insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","Fasher","900000000","update","delete");
insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","Pompis","900000000","update","delete");
insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","Grecia","900000000","update","delete");
insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","K'Taleya","900000000","update","delete");
insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","Caprichosas","900000000","update","delete");
insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","D'Rose","900000000","update","delete");
insert into enterprise(icon,name,telephone,update_field,delete_field)values("apartment","Frenetik","900000000","update","delete");

describe color;
insert into color(icon,name,update_field,delete_field)values("invert_colors","gris","update","delete");
insert into color(icon,name,update_field,delete_field)values("invert_colors","blanco","update","delete");
insert into color(icon,name,update_field,delete_field)values("invert_colors","negro","update","delete");
insert into color(icon,name,update_field,delete_field)values("invert_colors","rojo","update","delete");
insert into color(icon,name,update_field,delete_field)values("invert_colors","acero","update","delete");
insert into color(icon,name,update_field,delete_field)values("invert_colors","verde limon","update","delete");
insert into color(icon,name,update_field,delete_field)values("invert_colors","azulino","update","delete");
insert into color(icon,name,update_field,delete_field)values("invert_colors","guinda","update","delete");
insert into color(icon,name,update_field,delete_field)values("invert_colors","lila","update","delete");

insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 0","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 2","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 4","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 6","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 8","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 10","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 12","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 14","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 16","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 26","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 28","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 30","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 32","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 34","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 36","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 38","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 40","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 42","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 42","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 44","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 46","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla 48","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla S","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla M","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla L","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla XS","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla XL","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla XXL","update","delete");
insert into size(icon,name,update_field,delete_field)values("squared_foot","Talla XXXL","update","delete");

insert into location(icon,enterprise_id,update_field,delete_field)values("file_map",1,"update","delete");
insert into location(icon,enterprise_id,update_field,delete_field)values("file_map",2,"update","delete");